<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Testing Suite" duration-ms="131753" started-at="2019-09-29T17:31:59Z" finished-at="2019-09-29T17:34:11Z">
    <groups>
    </groups>
    <test name=" TestOvenStory" duration-ms="131753" started-at="2019-09-29T17:31:59Z" finished-at="2019-09-29T17:34:11Z">
      <class name="com.OvenStory.Assignment.testcases.OvenStoryMainPageTest">
        <test-method status="PASS" signature="initialisation()[pri:0, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="initialisation" is-config="true" duration-ms="68819" started-at="2019-09-29T23:00:50Z" finished-at="2019-09-29T23:01:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialisation -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="setUp" is-config="true" duration-ms="22" started-at="2019-09-29T23:01:59Z" finished-at="2019-09-29T23:01:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="VerifyAddProducttoCart()[pri:1, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="VerifyAddProducttoCart" duration-ms="59496" started-at="2019-09-29T23:01:59Z" finished-at="2019-09-29T23:02:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyAddProducttoCart -->
        <test-method status="PASS" signature="VerifySideMenuLinks()[pri:2, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="VerifySideMenuLinks" duration-ms="24462" started-at="2019-09-29T23:02:59Z" finished-at="2019-09-29T23:03:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifySideMenuLinks -->
        <test-method status="FAIL" signature="VerifyChangeLocation()[pri:3, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="VerifyChangeLocation" duration-ms="47060" started-at="2019-09-29T23:03:23Z" finished-at="2019-09-29T23:04:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Location Text are not Different expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Location Text are not Different expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at com.OvenStory.Assignment.testcases.OvenStoryMainPageTest.VerifyChangeLocation(OvenStoryMainPageTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyChangeLocation -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.OvenStory.Assignment.testcases.OvenStoryMainPageTest@3c0ecd4b]" name="tearDown" is-config="true" duration-ms="833" started-at="2019-09-29T23:04:11Z" finished-at="2019-09-29T23:04:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.OvenStory.Assignment.testcases.OvenStoryMainPageTest -->
    </test> <!--  TestOvenStory -->
  </suite> <!-- Testing Suite -->
</testng-results>
